### ISSUE TITLE
27-11-2014: Persgroep

### ISSUE THREAD

**Issue by mathiasbynens** [fronteersbe/meetups#13]
- [x] Contactpersoon: @bengie
- [x] Locatie: De Persgroep Publishing, Brusselsesteenweg 347, 1730 Asse (Kobbegem)
- [x] Capaciteit: 60 personen
- [x] Intro: Harald Bertels (@Bizonder) over "Design collaboration"
- [x] Presentatie 1: Pieter Mergan (@FirstManOnDaMoo) over "Schema.org microdata"
- [x] Presentatie 2: Jochen Vandendriessche (@joggink) over “Large Scale JavaScript Design Patterns (and how we use them at De Persgroep)”
- [x] Detailpagina: https://fronteers.nl/bijeenkomsten/2014/persgroep
- [x] Blog-post: https://fronteers.nl/blog/2014/11/bijeenkomst-persgroep
- [x] Tweet: https://twitter.com/fronteersbe/status/531802291943526400
- [x] Lanyrd-pagina: http://lanyrd.com/2014/fronteersbe-persgroep/
- [x] Verantwoordelijke bedankingen: @bengie

**Comment by IbeVanmeenen** [comment]
Deze mag ook op closed gezet worden veronderstel ik :)
