### ISSUE TITLE
2015-03-12: Digiti

### ISSUE THREAD

**Issue by stijnj** [fronteersbe/meetups#15]
- [x] Contactpersoon: @Berttimmermans
- [x] Locatie: Digiti, Zoersel
- [x] Capaciteit: 50 personen
- [x] Presentatie 1: Minecraft in de browser door @Berttimmermans
- [x] Presentatie 2: Contentstrategie door Saskia Videler
- [x] Detailpagina: https://fronteers.nl/bijeenkomsten/2015/digiti
- [x] Blog-post: https://fronteers.nl/blog/2015/02/bijeenkomst-digiti
- [x] Lanyrd-pagina: http://lanyrd.com/2015/fronteersbe-digiti/
- [x] Tweet: https://twitter.com/fronteersbe/status/566222023127744512

**Comment by wesleylancel** [comment]
Ha @Berttimmermans, hadden jullie toevallig al enig zicht op een datum? Dan kunnen wij op zoek naar een tweede spreker :)

**Comment by mathiasbynens** [comment]
De datum werd vastgelegd op donderdag 12 maart.

**Comment by wesleylancel** [comment]
Tweede spreker toegevoegd.

**Comment by mathiasbynens** [comment]
- [x] Detailpagina: https://fronteers.nl/bijeenkomsten/2015/digiti
- [x] Blog-post: https://fronteers.nl/blog/2015/02/bijeenkomst-digiti
- [x] Lanyrd-pagina: http://lanyrd.com/2015/fronteersbe-digiti/
- [x] Tweet: https://twitter.com/fronteersbe/status/566222023127744512

**Comment by IbeVanmeenen** [comment]
Deze mag ook geüpdatet worden? (kan zelf labels enzo niet aanpassen)

**Comment by mathiasbynens** [comment]
@IbeVanmeenen Nu wel :) Ik laat deze aan jou over!

**Comment by IbeVanmeenen** [comment]
@mathiasbynens awesome, thx :)

**Comment by IbeVanmeenen** [comment]
@mathiasbynens alhoewel, ik kan precies toch niks aanpassen... :(

**Comment by wesleylancel** [comment]
@IbeVanmeenen Nu beter?

**Comment by IbeVanmeenen** [comment]
@wesleylancel yes, thx :)
