### ISSUE TITLE
2015-04-28: 3Sign

### ISSUE THREAD

**Issue by bengie** [fronteersbe/meetups#16]
- [x] Contactpersoon: @bengie
- [x] Locatie: 3Sign, Boelare 116, 9900 Eeklo
- [x] Capaciteit: 30 personen
- [x] Presentatie 1:"De mythe van het extra werk van de AnySurfer richtlijnen" door Bart De Clercq (AnySurfer)
- [x] Presentatie 2: "HELP! De designer werkt met Illustrator" + "Introductie in Sketch en Zeplin" door Dries van Giel (3Sign)
- [x] Detailpagina: <https://fronteers.nl/bijeenkomsten/2015/3sign>
- [x] Blog-post: <https://fronteers.nl/blog/2015/03/bijeenkomst-3sign>
- [x] Lanyrd-pagina: <http://lanyrd.com/2015/fronteersbe-3sign/>
- [x] Tweet: <https://twitter.com/fronteersbe/status/581054754522062848>
- [x] Catering: ja, er zullen hapjes (pizzamobiel met verse pizza) en drank worden voorzien

**Comment by bengie** [comment]
Voorlopige datum: in de week van 23 feb als we sprekers vinden tegen dan. @wesleylancel @mathiasbynens moet dit op een donderdag? Ik zou het eens op een andere dag willen want ik hoor dat er sommige fronteers niet kunnen komen omdat het telkens op donderdag is.

Heb gevraagd aan 3Sign of zij nog sprekers weten (al dan niet in-house)

**Comment by stijnj** [comment]
Er was ook vraag van Digiti om een bijeenkomst in diezelfde periode te
doen: https://github.com/fronteersbe/meetups/issues/15

Ik zou deze eventueel proberen te verplaatsen naar einde maart aangezien we
voor Digiti al 1 spreker hebben?

Met vriendelijke groeten,

Stijn Janssen
0479 95 89 08

2015-01-16 8:06 GMT+01:00 Gregory Van Looy <notifications@github.com>:

**Comment by bengie** [comment]
@stijnj ok, ik geef het door aan 3Sign

**Comment by wesleylancel** [comment]
@bengie Overigens is voor mij donderdag geen must... Misschien wel handig dat dat nu een vast iets is, maar er zullen ook mensen zijn die nooit op donderdag kunnen dus wel eens goed op een andere dag.

**Comment by bengie** [comment]
Vermits Digiti op 12 maart valt, gaan we deze dan ook nog in maart organiseren?

**Comment by wesleylancel** [comment]
@bengie Misschien beter om voor april te gaan inderdaad. Kunnen zij met wat data komen die mogelijk zouden zijn?

**Comment by wesleylancel** [comment]
@bengie Enig idee of eind april zou gaan lukken?

**Comment by bengie** [comment]
@wesleylancel eind april lukt zeker MAAR ...

weten jullie nog iemand om te spreken als 2de spreker? Desnoods een groentje (als spreker) of iemand die allang twijfelt om te spreken. Ofwel doen we een oproep of er geinteresseerde sprekers zijn.

Ik heb 3Sign gevraagd om zelf ook voor een spreker te zorgen. Ik zal nog eens met hen afchecken voor een definitieve datum en hun spreker.

**Comment by wesleylancel** [comment]
@bengie Normaal zou dat wel moeten lukken. Er is nog een lijstje waar we op kunnen kijken en anders kunnen we altijd een oproep doen inderdaad. Meestal doen we dat wel pas als er een definitieve datum is, dus laten we die even afwachten.

**Comment by bengie** [comment]
Heb net Bart De Clerq van AnySurfer wat aangepord om een presentatie te doen. Dus dat is al 1. Ik zal nog eens horen bij 3Sign hoe het zit met hun spreker en topic

**Comment by bengie** [comment]
@wesleylancel en/of @stijnj is het nog niet stilletjesaan tijd om deze bijeenkomst aan te kondigen ?

**Comment by wesleylancel** [comment]
Ha @bengie, sorry, ik heb geen mail gehad van de wijziging van de titel en dacht eigenlijk dat er dus nog geen datum bekend was. Top dat alles rond is!

Ik zal proberen deze bijeenkomst later deze week even aan te kondigen, tenzij iemand eerder tijd heeft. /cc @stijnj @mathiasbynens

**Comment by mathiasbynens** [comment]
Ik heb de Lanyrd-pagina aangemaakt, alsook de detailpagina op fronteers.nl + de blog-post klaargezet. @wesleylancel, publiceer jij deze later deze week? Bedankt!

**Comment by bengie** [comment]
@stijnj @wesleylancel @mathiasbynens : wanneer gaan we het tweeten?

**Comment by mathiasbynens** [comment]
@bengie Ik heb het net live gezet:

* Detailpagina: <https://fronteers.nl/bijeenkomsten/2015/3sign>
* Blog-post: <https://fronteers.nl/blog/2015/03/bijeenkomst-3sign>
* Lanyrd-pagina: <http://lanyrd.com/2015/fronteersbe-3sign/>
* Tweet: <https://twitter.com/fronteersbe/status/581054754522062848>

Misschien nuttig om nog even te wachten tot na de middagpauze met de (re)tweets?

**Comment by wesleylancel** [comment]
Hi guys,

Het gaat mij helaas niet lukken om bij deze bijeenkomst te zijn. Is er iemand voor de 28e in de buurt van Limburg waaraan ik de camera kan meegeven om de talks op te nemen?

@stijnj Jij gaat niet of wel?

- Wesley

**Comment by stijnj** [comment]
Ik zal er zijn!

**Comment by wesleylancel** [comment]
@stijnj Zou je dan ook video willen opnemen? Indien ja moeten we even kijken om de camera voor die tijd bij jou te krijgen.

**Comment by stijnj** [comment]
Dat moet lukken, ben je die dag thuis? Dan kan ik vlak voor ik vertrek de
camera oppikken.

**Comment by wesleylancel** [comment]
Nope, dat is mijn tweede werkdag in Alken. Eventueel kan ik de camera voor die tijd wel even langs brengen bij Inventis, tweede helft volgende week zou dat moeten lukken.

**Comment by stijnj** [comment]
Perfect!

**Comment by stijnj** [comment]
@wesleylancel Ik zit ondertussen ook met een dubbele boeking waar ik niet onder uit kan. Eeklo is een hele afstand rijden en dan ga ik er nooit op tijd zijn.

Het zal dus een keertje zonder camera zijn...

**Comment by wesleylancel** [comment]
@stijnj Helaas, niks aan te doen.

**Comment by mathiasbynens** [comment]
’t Was `{interess,plez}ant`, en er was pizza!
