### ISSUE TITLE
2015-11-19: Kunstmaan

### ISSUE THREAD

**Issue by IbeVanmeenen** [fronteersbe/meetups#17]
- [x] Contactpersoon: @Sambego 
- [x] Locatie:
Kunstmaan, Ubicenter, Philipssite 5 Ingang C, 3000 Leuven, Niveau -1
- [x] Capaciteit: 175
- [x] Presentatie 1: "Web-audio-api en de web-midi-api" door @Sambego
- [x] Presentatie 2: "Starten met es6" door @diskwriter
- [x] Presentatie 3: "Hybrid Apps met Ionic Framework" door @bramus
- [x] Detailpagina: https://fronteers.nl/bijeenkomsten/2015/kunstmaan
- [x] Blog-post: https://fronteers.nl/blog/2015/10/bijeenkomst-kunstmaan
- [x] Lanyrd-pagina: http://lanyrd.com/2015/fronteersbe-kunstmaan/
- [x] Catering: Ja, er zullen hapjes en drank worden voorzien

**Comment by IbeVanmeenen** [comment]
Datum zou rond September/Oktober 2015 zijn.

**Comment by wesleylancel** [comment]
@IbeVanmeenen Top! Laten we ongeveer 2-3 maanden van te voren kijken om een definitieve datum af te spreken en verdere details af te stemmen.

**Comment by Sambego** [comment]
We zouden willen beginnen met het concreet vastleggen van de datum en de plaats voor deze meetup. Kan deze nog steeds doorgaan in september/oktober?
De meetup zal waarschijnlijk doorgaan hier in het ubicenter te Leuven, maar dat bevestig ik later nog.

@IbeVanmeenen zal vervangen worden door @diskwriter.

**Comment by wesleylancel** [comment]
Indien mogelijk zou ik de voorkeur geven aan september, in oktober is de conferentie van Fronteers zelf al. Verder lijkt me dat geen enkel probleem. Als jullie zelf met een paar mogelijke data kunnen komen zullen we beginnen met een van die vast te leggen en vanuit daar verder vertrekken.

**Comment by Sambego** [comment]
Perfect, dan gaan we eens kijken waneer we een ruimte ter beschikking kunnen stellen. Ik laat die zo snel mogelijk weten.

**Comment by IbeVanmeenen** [comment]
Alvast de namen aangepast in de bovenste comment :)

**Comment by Sambego** [comment]
We willen de meetup in de week van de 21ste september organiseren. Het maak in principe niet uit welke dag maar een donderdag lijkt me wel geschikt :) 
De meetup zal doorgaan in het auditorium bij ons in het gebouw.

> Ubicenter
> Philipssite 5 Ingang C
> 3000 Leuven
> Niveau -1

Hier kan maximaal 175 man in, maar aan zoveel volk denk ik niet dat we gaan geraken :)
Er was van ons bedrijf uit ook interesse om naast de talks van @diskwriter en mezelf een bekendere spreker uit te nodigen. Lijkt dit jullie een goed idee, en hebben jullie misschien wat tips, of gegevens contactpersonen om dit te realiseren?

**Comment by wesleylancel** [comment]
Als jullie voor de donderdag willen gaan is dat wat mij betreft prima. Kunnen we de datum dan definitief vastpinnen op 24 september?

Een extra spreker lijkt me altijd goed, meestal spreekt er sowieso nog iemand naast de talks van het gastbedrijf. Als we inderdaad de datum vast kunnen zetten zullen we op zoek gaan naar een spreker. Wij hebben sowieso een lijst met mensen die we kunnen benaderen.

**Comment by Sambego** [comment]
Dan doen we het donderdag de 24ste!

**Comment by Sambego** [comment]
@wesleylancel de 24ste was dan toch niet mogelijk voor ons, maar laten we het dan gewoon officieel zetten op woensdag 23 september :)

**Comment by wesleylancel** [comment]
Ah, sorry. Zal het aanpassen!

**Comment by wesleylancel** [comment]
Hi @Sambego,

Door drukte is het helaas niet gelukt om nog een derde spreker te vinden. Ik stel dus voor om het voor deze keer met twee sprekers van jullie te doen, tenzij iemand hier nog last minute een oplossing weet.

Ik denk dat we later deze weet de bijeenkomst zullen aankondigen.

**Comment by wesleylancel** [comment]
@Sambego @diskwriter: Zouden jullie nog het onderwerp van jullie talk en een korte beschrijving kunnen doorgeven?

**Comment by Sambego** [comment]
@wesleylancel mijn talk zal gaan over het gebruiken en bewerken van geluiden via de web-audio api en de web-midi api.

**Comment by Sambego** [comment]
@wesleylancel door de drukte bij ons op Kunstmaan heeft @diskwriter geen tijd om zijn presentatie voor te bereiden. Hierdoor stel ik voor dat we de meetup uitstellen zodat hij tijd heeft hiervoor, en we misschien ook een 3de spreker kunnen vinden. Dit zal dan waarschijnlijk ergens na de Fonteers conference zijn.

**Comment by bramus** [comment]
Ik kan eventueel tegen dan wel wat uit m'n mouw schudden. Over Hybrid apps met Ionic bvb.

**Comment by Sambego** [comment]
@bramus merci voor het voorstel, maar we hebben de aula bij ons in het gebouw al afgezegd ondertussen. Je bent altijd welkom om op de later datum te komen spreken :)

**Comment by wesleylancel** [comment]
@Sambego Oké, prima, komt misschien wel goed uit dat we dan inderdaad nog een derde spreker kunnen vinden. Ik denk overigens dan @bramus doelde op die latere datum.

Zouden jullie anders met een of meerdere data kunnen komen in de tweede helft van oktober of november? Als @bramus dan ook kan hebben we in ieder geval de sprekers rond :)

**Comment by bramus** [comment]
Week van 26/10/2015 lukt hier, alsook de week van 16/11/2015.

**Comment by Sambego** [comment]
We dachten het begin november te doen, wat denk je van de 19de?

**Comment by wesleylancel** [comment]
Wat mij betreft oké, gaat dat voor jou lukken @bramus?

**Comment by bramus** [comment]
19/11 is prima!

**Comment by wesleylancel** [comment]
Top! Titel aangepast naar 19 november. Zal het asap aan de agenda op de site toevoegen, en half oktober ongeveer een aankondiging doen.

@bramus @Sambego @diskwriter: zouden jullie voor die tijd ergens een titel en beschrijving van een zin of 2 kunnen doorgeven? Alvast dank!

**Comment by Sambego** [comment]
Prima!

Mijn talk zal nog steeds gaan over de web-audio-api, en de web-midi-api.

**Comment by bramus** [comment]
Hier de titel "Hybrid Apps met Ionic Framework" ... zo kan ik nog alle
kanten uit ;-)

B!

**Comment by wesleylancel** [comment]
Thx @Sambego @bramus. @diskwriter, heb jij ook al enig idee?

**Comment by diskwriter** [comment]
Waarschijnlijk iets over starten met es6, maar kan nog veranderen! 
(Sorry voor de vertraging :) )

**Comment by wesleylancel** [comment]
Thanks! Heb het erop gezet, over een week of twee zal ik de aankondiging maken.

**Comment by wesleylancel** [comment]
@Sambego Wil deze graag morgen of vrijdag aankondigen, check dat alles oke is in de eerste comment?

**Comment by Sambego** [comment]
@wesleylancel Alles is ok :)

**Comment by Sambego** [comment]
@wesleylancel enig idee, wanneer je de meetup juist gaat aankondigen?

**Comment by wesleylancel** [comment]
@Sambego Ik ben nu alles klaar aan het zetten, blogpost gaat dan morgen live en zal dan ook op Twitter zetten. Zal de links hier zo vast plaatsen.

**Comment by wesleylancel** [comment]
@Sambego Detailpagina staat klaar op https://fronteers.nl/bijeenkomsten/2015/kunstmaan. Blogpost staat ook klaar om morgen live te gaan. /cc @diskwriter @bramus

**Comment by wesleylancel** [comment]
@mathiasbynens of @stijnj: zou een van jullie een Lanyrd event kunnen aanmaken en evt linken op de detailpagina?

**Comment by Sambego** [comment]
Thanks @wesleylancel!

**Comment by stijnj** [comment]
Event aangemaakt een pagina aangepast. Ik heb wel geen toegang tot de fronteers(be) account op Lanyard. Die dat wel heeft kan evt. het event nog claimen.

https://fronteers.nl/bijeenkomsten/2015/kunstmaan

**Comment by mathiasbynens** [comment]
@stijnj Er is geen Fronteers(be)-account voor Lanyrd. Het Lanyrd-event aanmaken en beheren deed ik gewoon vanaf m’n eigen account, hoor. Je kan via “Claim” toegang krijgen tot de uitgebreide admin-mogelijkheden.

http://lanyrd.com/2015/fronteersbe-kunstmaan/

**Comment by IbeVanmeenen** [comment]
Moeten we nog een verantwoordelijke aanstellen voor de bedanking?

**Comment by wesleylancel** [comment]
@IbeVanmeenen dat zal ik oppakken, heb nog een voorraadje thuis liggen :)

**Comment by diskwriter** [comment]
Even voorstellen: Wij zitten met een aantal niet nederlandstalige mensen. Zou het een probleem zijn als we de talks in het Engels doen? Zo kunnen zij ook volgen...

**Comment by wesleylancel** [comment]
Wat mij betreft is dat oké als dat voor @bramus ook goed is. Zou het dan wel zo snel mogelijk willen communiceren zodat mensen er rekening mee kunnen houden.

**Comment by bramus** [comment]
Yes yes, very exciting! En al. ;-)

2015-10-29 10:17 GMT+01:00 Wesley Lancel <notifications@github.com>:

**Comment by stijnj** [comment]
@bramus @diskwriter @IbeVanmeenen 

Kunnen jullie ook links bezorgen naar jullie presentaties?

**Comment by bramus** [comment]
http://www.slideshare.net/bramus/hybrid-apps-with-ionic-framework

2015-11-25 9:11 GMT+01:00 Stijn Janssen <notifications@github.com>:

**Comment by Sambego** [comment]
Van Ibe ga je geen slides krijgen vrees ik :)
https://sambego.github.io/pedalboard-presentation/#/

**Comment by stijnj** [comment]
My bad!

**Comment by diskwriter** [comment]
https://speakerdeck.com/diskwriter/getting-started-in-es6

**Comment by Sambego** [comment]
@wesleylancel heb je enig idee wanneer de video's op de fronteers vimeo komen?

**Comment by wesleylancel** [comment]
Nog niet direct een idee, ik laat wat weten zodra ik meer weet!
