### ISSUE TITLE
2015-11-12 - The Creativity Gym

### ISSUE THREAD

**Issue by stijnj** [fronteersbe/meetups#18]
- [x] Contactpersoon: @iamgoodbytes
- [x] Locatie: The Creativity Gym, Mechelen
- [x] Capaciteit: Max 100
- [ ] Presentatie 1: @boyofgreen - tba
- [ ] Presentatie 2: n/a
- [ ] Detailpagina: ?
- [ ] Blog-post: ?
- [ ] Tweet: ?
- [ ] Lanyrd-pagina: ?
- [ ] Verantwoordelijke bedankingen: ?

**Comment by iamgoodbytes** [comment]
Capaciteit: max 100
Soundsystem aanwezig met twee headsets voor de sprekers
Locatie ziet er ongeveer zo uit: http://www.thecreativitygym.be/event/imd-invites-musketon

**Comment by stijnmichiels** [comment]
Datum gevonden (in samenspraak met @iamgoodbytes): 12 november 's avonds!

Ook meteen één spreker bevestigd: @boyofgreen (die toevallig rond die periode in het land is ^^)

**Comment by wesleylancel** [comment]
@stijnmichiels: Top dat deze bijeenkomst nog door kan gaan, alleen is 12 november wel erg kortdag. Meestal proberen we ongeveer een maand van te voren de bijeenkomst aan te kondigen. Daarnaast is er precies een week later al een bijeenkomst, meestal proberen we dat ook wat te spreiden. Is het nog mogelijk om die datum wat te verlaten?

**Comment by bramus** [comment]
Lijkt me inderdaad niet zo interessant om twee bijeenkomsten opeen te plannen. Lijkt me ook beter om 'm door te schuiven.

**Comment by stijnmichiels** [comment]
Datum was gekozen op basis van beschikbaarheid de spreker. Zijn 2 events op 1 maand een grote no-go?

**Comment by stijnj** [comment]
Ideaal is het niet, maar een no-go is het nooit imho.

Zeker als het over een internationale spreker gaat.

**Comment by iamgoodbytes** [comment]
Iemand moet hier de knoop doorhakken denk ik? Wat locatie betreft is er nooit een probleem, datum is daar flexibel.

**Comment by stijnj** [comment]
Dan hak ik de knoop door. 

Als we een internationale spreker kunnen krijgen moeten we de kans grijpen. Zonder twijfel.

**Comment by wesleylancel** [comment]
Laten we dan proberen vandaag nog een aankondiging te doen! Ik stel voor om het dan bij 1 spreker te houden. @iamgoodbytes @stijnmichiels: Weten jullie waar de talk over zal gaan en hoe lang deze ongeveer zal duren?

**Comment by stijnmichiels** [comment]
Topics die Jeff voorstelde, have your pick :)  
- Why the hell do we need another new browser: The anatomy of Microsoft Edge, and the impact it will have on the web.
- Webapps living outside the browser: there are a number of converging standards and tools that are making webapps portable.  From cross-browser to cross-device
- Manifoldjs: exploring this new Open source tool that brings web apps to app stores, while maintaining the integrity of the web.
- Behold the power of the W3C Web App Manifest:  this is the standard that could change everything

Talk van een uurtje? Kan me inbeelden dat Q&A (mits dat organisatorisch haalbaar is) ook nuttig kan zijn?

**Comment by wesleylancel** [comment]
Lengte van een uurtje + dan nog wat Q&A lijkt me perfect.

Wat betreft het onderwerp, ik heb geen specifieke voorkeur, dus dat laat ik aan jullie / hem over.

**Comment by stijnj** [comment]
Mijn voorkeur gaat uit naar de 2e, of de 1e.

**Comment by bengie** [comment]
voor mij ook het 1ste of 2de

**Comment by stijnmichiels** [comment]
Dan stel ik voor om 1 & 2 te mixen. Ze liggen niet verrassend ver uit elkaar :)
@iamgoodbytes zou een landingspagina klaar staan hebben, hebben we nog iets nodig vooraleer registraties opengezet kunnen worden?

**Comment by wesleylancel** [comment]
@stijnmichiels Heb je een definitieve titel en eventueel een kort tekstje die ik bij de talk kan zetten op de aanmeldpagina?

**Comment by stijnmichiels** [comment]
> ##Microsoft Edge is not just another new browser
>
>Jeff Burtoft (HTML5 Evangelist at Microsoft) will explain the anatomy of Microsoft Edge and the impact it will have on the web. This next-generation browser is built into Windows 10 and respects all the things we appreciate and love as front end developers. 
> But there is more. A number of converging standards and tools are making webapps portable. Our web platform allows you to leverage your HTML skills from cross-browser to cross-device. Come and hear what you can do more with the knowledge you already have. 

sounds good? :)

**Comment by wesleylancel** [comment]
@stijnmichiels Top! Enige wat ik even niet terug kan vinden is of er hapjes en drankjes worden voorzien?

**Comment by stijnmichiels** [comment]
Wat ik begrepen had van @iamgoodbytes: pintjes: yes, food: no. 

Ik doublecheck nog even om helemaal zeker te zijn voor evt versnaperingen :)

**Comment by wesleylancel** [comment]
@stijnmichiels Oke,vermeld ik het voor nu zo, kan nog aangepast worden. Mis toch nog iets, het adres ;)

**Comment by iamgoodbytes** [comment]
Zit momenteel in ziekenhuis dus kan niet altijd snel antwoorden maar:

- zaal in orde
- pintjes en frisdrank zijn geregeld
- broodjes normaal niet maar ik pols of we die ook kunnen sponsoren, straks duidelijkheid
- adres: Creativity Gym op Thomas More Mechelen Campus Kruidtuin. Lange Ridderstraat 44 in 2800 Mechelen 
- ik voorzie nog wat info ivm parkeren

**Comment by wesleylancel** [comment]
Thanks! Verdere info kunnen we nog aanvullen, link staat klaar: https://fronteers.nl/bijeenkomsten/2015/the-creativity-gym. Ga nu tweeten. Alle retweets welkom :)

**Comment by iamgoodbytes** [comment]
@wesleylancel drinks zijn al geregeld, voor broodjes krijg ik helaas geen budget los op school. 

Instructies om er te raken en te parkeren zijn misschien handig voor de aanwezigen: 
![instructions](https://cloud.githubusercontent.com/assets/3899360/11043363/9f162158-871c-11e5-90a8-d5df97a2a997.png)

**Comment by wesleylancel** [comment]
@iamgoodbytes Thx! Zal het kaartje morgen toevoegen op de detailpagina. Geen probleem dat er geen budget is voor een hapje, ik kan nog even peilen bij Fronteers of er daar budget is, maar misschien is het ook al wat laat om dat nog geregeld te krijgen.

**Comment by JacoKoster** [comment]
Wesley, ik zie dat dit georganiseerd wordt door een non-profit, dan valt er zeker wat te regelen qua budget. Dit kun je gewoon declareren bij de penningmeester.

**Comment by wesleylancel** [comment]
@iamgoodbytes Voila :) Hebben jullie daar een vaste partner voor die dat eventueel nog geregeld krijgt? Indien dat lastig wordt laten we het gewoon zitten.

**Comment by iamgoodbytes** [comment]
Morgen ben ik op school en pols ik bij onze catering of dat nog kan. Wat ze me zeker gaan vragen is het aantal broodjes dat ze moeten maken.

**Comment by wesleylancel** [comment]
Dank, dan wachten we dat even af. Zou dan morgen tellen hoeveel aanmeldingen er zijn en er dan nog een hoopje bij optellen.

**Comment by iamgoodbytes** [comment]
@wesleylancel helaas lukt het voor de catering niet om hun bestellingen nog aan te passen. De feestdag van morgen zit er voor iets tussen. Er zijn wel genoeg food-opties in de buurt.

**Comment by wesleylancel** [comment]
@iamgoodbytes Oké, geen probleem. Dan kan er inderdaad vooraf gewoon in de buurt gegeten worden.

**Comment by wesleylancel** [comment]
Hoe is het geweest vorige week?

**Comment by iamgoodbytes** [comment]
Wat mij betreft een prima meetup, zeker om last-minute georganiseerd te zijn. Spreker was interessant zonder al teveel promo te maken voor Microsoft. Nut van manifoldjs was me wat vaag voor zijn talk, maar nadien bedacht ik dat ik wel vaak slack (hosted app in native container) gebruik. Een 40-a-50 aanwezigen. Fronteers is steeds welkom voor een volgende meetup wat mij betreft!

https://twitter.com/stijnj/status/664870815981248512
![ctoyeifu8aaljma](https://cloud.githubusercontent.com/assets/3899360/11181059/a6399c06-8c5f-11e5-8176-235b7618e8f1.jpg)

**Comment by wesleylancel** [comment]
Top, goed om te horen! :)

**Comment by stijnmichiels** [comment]
Feedback via via van de speaker (Jeff): heel tevreden van de organisatie, zeker gezien het last-minute aspect (dankuwel IMD!). Hij was onder de indruk van interesse, betrokkenheid & open mindset van de community. Een geslaagde avond in België, dankzij Fronteers :)
Gaf aan om dit met plezier opnieuw te willen doen als de gelegenheid zich opnieuw zou voordoen. 

Ik heb daar niets aan toe te voegen. Top avond! :)

**Comment by wesleylancel** [comment]
Goed om te horen! Dank alle betrokken partijen :)
