### ISSUE TITLE
2015-12-15 - Digiti

### ISSUE THREAD

**Issue by stijnj** [fronteersbe/meetups#20]
- [x] Contactpersoon: @Berttimmermans
- [x] Locatie: DIGITI, Diamantstraat 8. B-2200 Herentals
- [x] Capaciteit: 175
- [x] Presentatie 1: @Berttimmermans - Je eigen dashboard met HTML, CSS en JavaScript!
- [x] Presentatie 2: @julezrulez - A11Y/accessibility, toegankelijkheid op het web
- [x] Detailpagina: https://fronteers.nl/bijeenkomsten/2015/digiti-2
- [x] Blog-post: https://fronteers.nl/blog/2015/12/bijeenkomst-digiti
- [ ] Lanyrd-pagina: TBA
- [x] Catering: Ja, er zullen hapjes en drank worden voorzien

**Comment by wesleylancel** [comment]
@Berttimmermans Hebben jullie al enig zicht op een mogelijk datum in december? Ik denk dat de eerste helft van de maand beter is ivm de feestdagen. Meestal zijn de bijeenkomsten op donderdag, al hoewel dat voor mij geen must is.

**Comment by Berttimmermans** [comment]
@wesleylancel We hebben er juist over samen gezeten en we mikken op dinsdag 8 december OF donderdag 10 december. Verder zal ik een presentatie geven over het bouwen van een live dashboard, de titel en beschrijving voor de presentatie volgt vandaag nog. Hebben jullie al een tweede spreker gevonden?

**Comment by Berttimmermans** [comment]
Je eigen dashboard met HTML, CSS en JavaScript!
-----------------
Nadat hij eerder al zijn eigen versie van Pokémon en Minecraft aan jullie voorstelde, duikt Bert Timmermans nu samen met jou in de wereld van de dashboards. Hij start vanaf het design van zijn dashboard en loodst je stapsgewijs doorheen alle valkuilen en uitdagingen tijdens het opbouwen van zijn dashboard.

**Comment by wesleylancel** [comment]
Top! Dankjewel voor de snelle reactie. Op basis van die datums zullen we op zoek naar gaan naar een tweede spreker. Gaan jullie zelf nog uit een van die twee kiezen of is er geen specifieke voorkeur?

**Comment by Berttimmermans** [comment]
@wesleylancel voorkeur gaat lichtjes naar dinsdag maar we zijn daar flexibel in. Verder hebben we zeker plaatst voor +175 mensen en voorzien wij broodjes of iets gelijkaardig. Als adres mag je volgende meegeven:

DIGITI 
Diamantstraat 8 
B-2200 Herentals

**Comment by wesleylancel** [comment]
@Berttimmermans Ik zie net dat er op 10 december in NL een bijeenkomst is in Breda, Nederland. Laten we dan dus sowieso voor de dinsdag 8 december gaan.

**Comment by Berttimmermans** [comment]
👍

**Comment by Berttimmermans** [comment]
@wesleylancel Kunnen we de meetup nog verplaatsen naar de 15de december?

**Comment by wesleylancel** [comment]
Wat mij betreft kan dat. We gaan dan zsm op zoek naar een spreker.

**Comment by Berttimmermans** [comment]
@wesleylancel Hebben jullie ondertussen als een tweede spreker gevonden? Zodat we op tijd kunnen starten met communicatie langs onze kant ;-)

**Comment by wesleylancel** [comment]
Helaas nog niet. We zijn nog op zoek, vanochtend een tweet uitgestuurd. Hopelijk deze week nog.

**Comment by wesleylancel** [comment]
Tweede spreker is gevonden! De talk van @julezrulez gaat over A11Y/accessibility, toegankelijkheid op het web.

Ik probeer de aankondiging deze vrijdag live te hebben.

**Comment by Berttimmermans** [comment]
Wanneer mag ik jullie aankondiging verwachten?

**Comment by wesleylancel** [comment]
@Berttimmermans detailpagina staat live: https://fronteers.nl/bijeenkomsten/2015/digiti-2

Morgen volgen de blogpost en tweets!
