### ISSUE TITLE
2016-02-25 : Nucleus

### ISSUE THREAD

**Issue by TSchuermans** [fronteersbe/meetups#21]
- [x] Contactpersoon: Tom Schuermans (@tschuermans)
- [x] Locatie: Nucleus, Noorderlaan 133 bus 8, 2030 Antwerpen
- [x] Capaciteit: 50 personen
- [x] Presentatie 1: Mattias Geniar (@mattiasgeniar) - [HTTP/2: The Next Version of the Internet](https://speakerdeck.com/mattiasgeniar/2-the-next-version-of-the-internet)
- [x] Presentatie 2: Koen Kivits (@koenkivits) - Bowser in de browser
- [x] Detailpagina: https://fronteers.nl/bijeenkomsten/2016/nucleus
- [x] Blog-post: https://fronteers.nl/blog/2016/02/bijeenkomst-nucleus
- [x] Tweet: https://twitter.com/fronteersbe/status/696606045049901057
- [x] Lanyrd-pagina: ?
- [x] Verantwoordelijke bedankingen: @IbeVanmeenen 
- [x] Catering: Ja, er zullen hapjes en drank worden voorzien

<img width="922" alt="route parking" src="https://cloud.githubusercontent.com/assets/671116/11362767/07041d7c-9296-11e5-8a78-ebe57f367ebe.png">

**Comment by wesleylancel** [comment]
Thanks voor het aanmaken van een issue! Leuk dat jullie weer een bijeenkomst willen organiseren. Hebben jullie enig zicht op de maand waarin de meeting zal plaatsvinden? Gelijk in januari doen of misschien na de feestdagen eerst even tot februari wachten?

**Comment by TSchuermans** [comment]
Februari komt iets beter uit denk ik. Januari zit je idd met de feestdagen en ook PHP Benelux conference.

**Comment by wesleylancel** [comment]
Als het mogelijk is kunnen we nu best alvast een datum vastleggen zodat wij vroeg op zoek kunnen naar een spreker. Hebben jullie voorkeur?

**Comment by TSchuermans** [comment]
Liefst na 15 februari, datum is door jullie vrij te kiezen. Elke dag kan, buiten vrijdag.

**Comment by wesleylancel** [comment]
@TSchuermans Donderdag 25 februari als datum zetten?

**Comment by TSchuermans** [comment]
@wesleylancel Ok voor ons, staat hier alvast genoteerd.

**Comment by wesleylancel** [comment]
Tweede spreker aan de eerste post toegevoegd!

**Comment by wesleylancel** [comment]
Detailpagina staat klaar, blogpost gaat morgen live, tweet zal ik ook morgen doen. /cc @TSchuermans @koenkivits

**Comment by TSchuermans** [comment]
Mooi, ben benieuwd naar de opkomst.

**Comment by IbeVanmeenen** [comment]
Het was een gezellige avond! :-)

**Comment by stijnj** [comment]
👍
