### ISSUE TITLE
2016-03-24 - iDA Mediafoundry

### ISSUE THREAD

**Issue by stijnj** [fronteersbe/meetups#22]
- [x] Contactpersoon: Bert Swinnen
- [x] Locatie: Moonbeat, Mechelen
- [x] Capaciteit: 80 personen
- [x] Presentatie 1: Mario Van den Eynde over React
- [x] Presentatie 2: Johan Ronsse (@wolfr) over [Bedrock](http://bedrock.mono.company/)
- [x] Detailpagina: https://fronteers.nl/bijeenkomsten/2016/ida-mediafoundry
- [x] Blog-post: https://fronteers.nl/blog/2016/03/bijeenkomst-ida-mediafoundry
- [ ] Tweet: ?
- [x] Verantwoordelijke bedankingen: @stijnj
- [x] Catering: Broodjes

**Comment by BertSwin** [comment]
Datum: 24 maart
Locatie: Moonbeat, Mechelen
Catering: Broodjes

**Comment by wesleylancel** [comment]
Tweede spreker toegevoegd!

**Comment by BertSwin** [comment]
Spreker voor iDA Mediafoundry is Mario Van den Eynde.
"From null to full in under 30 minutes", building a React app.
