### ISSUE TITLE
2016-04-07 - Axxes IT

### ISSUE THREAD

**Issue by stijnj** [fronteersbe/meetups#23]
- [x] Contactpersoon: Toon Verbuyst
- [x] Locatie: Axxes IT, Antwerpen
- [ ] Capaciteit: ?
- [ ] Presentatie 1: ?
- [ ] Presentatie 2: ?
- [ ] Detailpagina: ?
- [ ] Blog-post: ?
- [ ] Tweet: ?
- [ ] Lanyrd-pagina: ?
- [x] Verantwoordelijke bedankingen: @stijnj
- [x] Catering: Ja

**Comment by TVerbuyst** [comment]
Stijn, overeengekomen met Yannick dat de meetup zal doorgaan op donderdag 7/04/2016.
Ik check met hem voor titel, detailpagina en 2de presentatie.
Locatie nog niet bevestigd, maar catering zal er zijn.

**Comment by IbeVanmeenen** [comment]
Alvast de data aangevuld

**Comment by TVerbuyst** [comment]
Alvast de invulling van de avond

18u: ontvangst

18.30u-19.15u: Yannick Houbrix - Future Proof Angular 1.x Applications
Met Angular 2 voor de deur rijst de vraag hoe we met Angular 1.x applicaties kunnen bouwen die future proof zijn. Deze sessie leert je hoe applicatie structuur, TypeScript en Webpack hierbij kunnen helpen.

19.15u-19.45u: Pauze

19.45u-20.30u: Brecht Billiet - Redux
Hoe helpt Redux je om je applicatie makkelijker begrijpbaar en testbaar te maken

20.30u- 22u: Après drink

De locatie zal op KT ingevuld worden. 

Mvg,
Toon

**Comment by TVerbuyst** [comment]
Capaciteit: 40-50 personen

**Comment by TVerbuyst** [comment]
Heren - korte heads up, met aanvulling van locatie+lichte wijziging aankomstuur.
inschrijvingen zouden wij beheren via Eventbrite - ok voor jullie?

17.30u: ontvangst + broodjeslunch

18.30u-19.15u: Yannick Houbrix - Future Proof Angular 1.x Applications
Met Angular 2 voor de deur rijst de vraag hoe we met Angular 1.x applicaties kunnen bouwen die future proof zijn. Deze sessie leert je hoe applicatie structuur, TypeScript en Webpack hierbij kunnen helpen.

19.15u-19.45u: Pauze

19.45u-20.30u: Brecht Billiet - Redux
Hoe helpt Redux je om je applicatie makkelijker begrijpbaar en testbaar te maken

20.30u- 22u: Après drink

De locatie: 
Ter Elst – zaal Van Eyck
Kattenbroek 1
2650 Edegem

**Comment by TVerbuyst** [comment]
info en inschrijvingen via:
www.axxes.com/blog

**Comment by wesleylancel** [comment]
Tweet geplaatst: https://twitter.com/fronteersbe/status/717337055831990276
