### ISSUE TITLE
2017-09-27 - Teamleader

### ISSUE THREAD

**Issue by IbeVanmeenen** [fronteersbe/meetups#24]
- [x] Contactpersoon Fronteers: Sam
- [x] Contactpersoon Locatie: [@lowiebenoot](https://twitter.com/lowiebenoot)
- [x] Locatie: Teamleader - Gent
- [x] Capaciteit: 50-60
- [x] Presentatie 1: @roelvangils - The state of WAI-ARIA
- [x] Presentatie 2: @tcoopman - Front-end microservices
- [x] Detailpagina: ?
- [x] Blog-post: ?
- [x] Tweet: ?
- [x] Lanyrd-pagina: ?
- [x] Verantwoordelijke bedankingen: ?
- [x] Catering: Yep

**Comment by Sambego** [comment]
Ik kan eventueel mijn ["I didn't know the browser could do that"](https://meow.sambego.be/) presentatie geven.

**Comment by roelvangils** [comment]
Ik heb al heel lang talks meer gegeven. Ik kan wel eens iets vertellen over the state of WAI-ARIA of zo.

**Comment by Sambego** [comment]
Lijkt me zeer interessant!

**Comment by tomjanssens** [comment]
Ik wil eventueel mijn "[Frontend on Steroids](https://www.timble.net/talks/2016/06/frontend-on-steroids/)" presentatie geven.

**Comment by bramus** [comment]
Dit lijkt me ook nog een interessante: https://twitter.com/robbert_wolfs/status/834523956187189249 (gespot via de lijst van CSS Day Attendees)

**Comment by WartClaes** [comment]
@bramus zeker een goede talk om te eens mee te krijgen denk ik
