### ISSUE TITLE
2018-??-?? - Hellogoodbye - Brugge

### ISSUE THREAD

**Issue by IbeVanmeenen** [fronteersbe/meetups#25]
- [ ] Contactpersoon Fronteers: Ibe Vanmeenen (@IbeVanmeenen)
- [ ] Contactpersoon Locatie: Mattias Strubbe (@mattiasstrubbe - Slack)
- [ ] Locatie: Koningin Astridlaan 97, 8200 Sint-Michiels - Brugge
- [ ] Capaciteit: 30-50
- [ ] Presentatie 1: ?
- [ ] Presentatie 2: ?
- [ ] Detailpagina: ?
- [ ] Blog-post: ?
- [ ] Tweet: ?
- [ ] Lanyrd-pagina: ?
- [ ] Verantwoordelijke bedankingen: Ibe Vanmeenen (@IbeVanmeenen)
- [ ] Catering: ?

**Comment by mattiasstrubbe** [comment]
### Contactpersoon Locatie
~~Mathias Strubbe (@mathiasstrubbe - Slack)~~ => Mattias Strubbe (@mattiasstrubbe - Slack)
GSM: 0472459111

### Locatie
Koningin Astridlaan 97, 8200 Sint-Michiels (Brugge)
Let op: Veel winkels op hetzelfde adres zonder duidelijke afsplitsing. 
De ingang van onze kantoren is rechts van de apotheek.

Mensen die met de trein komen kunnen buslijn 25 nemen (elke 20 min). 
Halte Sint-Michiels Grasdreef is recht voor de deur.

**Comment by IbeVanmeenen** [comment]
@mattiasstrubbe Thx voor de info, deze is alvast ingevuld.

- Ik heb qua capaciteit 30-50 voorlopig genoteerd. Voor de registratie anders afronden op 40 man maximum? 
- Daarnaast vroeg ik me af of jullie iets kunnen voorzien van broodjes of drankjes? Zeker geen must hoor, maar goed om te weten!
