### ISSUE TITLE
2017-11-30 - De Persgroep - Asse

### ISSUE THREAD

**Issue by IbeVanmeenen** [fronteersbe/meetups#30]
- [x] Contactpersoon Fronteers: De Persgroep, Asse
- [x] Contactpersoon Locatie: @bengie 
- [x] Locatie: De Persgroep, Asse
- [x] Capaciteit: 40
- [x] Presentatie 1: Joggink - Progressive Enhancement - How did we get here?
- [x] Presentatie 2: Bramus - ESNext – What's next for JavaScript?
- [x] Detailpagina: https://fronteers.nl/bijeenkomsten/2017/depersgroep
- [x] Meetup.com: https://www.meetup.com/Fronteers-BE/events/244086094/
- [x] Verantwoordelijke bedankingen: @bengie 
- [x] Catering: Yes (Broodjes)
- [x] Datum: 30/11/2017

**Comment by bramus** [comment]
- Joggink kan wel eens komen ranten over Progressive Enhancement

- ik kan zelf eens wat tegengewicht in de schaal proberen leggen en over
React de boel wat aaneenpraten

**Comment by bengie** [comment]
Lokatie: De Persgroep, Asse 
Datum: november of december
Presentatie 1 : Joggink
Presentatie 2 : Bramus en/of bij DPP wil Jeroen VdB ook wel eens praten over performance
Catering: De Persgroep - broodjes
Bedankingen: Bengie

**Comment by bengie** [comment]
Heb zelfs nog ne kandidaat om te spreken op ne meetup. Dat kan ook op een andere datum.
Yannick Van Avermaet, frontend architect bij De Persgroep wil wel eens spreken over web security.

**Comment by IbeVanmeenen** [comment]
Super, bedankt @bramus en @bengie . Met wie van de Persgroep zouden we een datum kunnen vastleggen? Of kan dit via jouw @bengie? Ik zou voorstellen eind November dan

**Comment by bengie** [comment]
@IbeVanmeenen ik regel alles wel bij de Persgroep. Ik hou jullie wel op de hoogte qua data etc.. Moet nog checken wanneer t auditorium vrij is eind november

**Comment by bramus** [comment]
Zet anders gerust Yannick op't programma, dan is't een thuismatch voor hem ;)

**Comment by bengie** [comment]
Ok, @bramus ik check t af met Yannick. Moest t nu om de een of andere reden niet lukken voor hem om dan presentatie te geven dan laat ik u TIJDIG iets weten

**Comment by bramus** [comment]
Definieer TIJDIG 😂😂😂

**Comment by bengie** [comment]
goh, in de vroege namiddag van de dag zelve. T is Roel toch ook gelukt  😂😂😂

**Comment by IbeVanmeenen** [comment]
Super, thanks @bengie ! Enig idee hoeveel man er in het auditorium binnen kan?

**Comment by bengie** [comment]
veel .... maar ik stel voor dat we t rond 30 à 40-tal kunnen houden. Gewoonlijk daagt er toch niet veel meer dan 30 man op (tenzij we het op een hogeschool organiseren ofzo).
Ik hoop dat e rook nog wat frontenders van De Persgroep opdagen die we gewoonlijk niet op een fronteers meetup zien, dus daarom een 40 plaatsen vrijhouden.

**Comment by bramus** [comment]
In totaal is dat dan 70 man in bengie-math (30 inschrijvingen + 40
vrijhouden), of snap ik het niet goed? :-P

Sowieso mag je der van uit gaan dat er minsten 10 man niet komt opdagen,
dus je kan/mag gerust ruimer gaan met de online inschrijvingen.

B!

**Comment by bengie** [comment]
@IbeVanmeenen 

Datum: donderdag 30 november
Max aantal plaatsen: 40
Deuren open vanaf 18u
Catering: broodjes en drank, achteraf ook bier

**Comment by bengie** [comment]
@bramus de Yannick durft ni ;-)  Dus t zal toch aan u zijn. Kunt gij op 30/11 ?

We organiseren volgend jaar er dan nog wel eens ene bij DPP en dan moet Yannick maar spreken.

**Comment by joggink** [comment]
Haha!

Ik ga dan eens aan mijn preso beginnen peizek

**Comment by yvanavermaet** [comment]
@bengie loser :p 
First come, first serve (en ik wou enkel als backup, moesten er te weinig zijn): @bramus you're up!

We doen begin volgend jaar gewoon nog enen bij de Persgroep en dan zal ik spreken ;-)

**Comment by bramus** [comment]
Allrighty. Dan pin ik m'n onderwerp vast op "ESNext – What's next for JavaScript?"

**Comment by IbeVanmeenen** [comment]
Super. Thanks all!

**Comment by IbeVanmeenen** [comment]
@joggink Mag ik voor jouw presentatie "Progressive Enhancement" voorlopig vastleggen? :)

**Comment by joggink** [comment]
Jup, maar wel met de titel 'How did we get here?'

**Comment by IbeVanmeenen** [comment]
@joggink & @bramus kunnen jullie me ook kleine intro naar de talk bezorgen? (mag zeer beknopt zijn hoor) Thanks :-)

**Comment by bramus** [comment]
Hierzo:

> Sinds de komst van ES6 (ES2015) gaat het snel vooruit in JavaScript-land. Minder bekend (en minder groot in omvang) zijn de ES2016 en ES2017 releases. Deze talk werpt niet alleen een blik op deze twee releases, maar ook op nieuwe JavaScript features die er aan zitten te komen.

**Comment by bengie** [comment]
@IbeVanmeenen je mag het bezoekersaantal al verhogen naar 60. Voorlopig zijn er nog maar 2 plaatsen vrij

**Comment by Sambego** [comment]
@bengie het bezoekersaantal is verhoogd :)

**Comment by bengie** [comment]
@Sambego sturen jullie nog een tweet dat er extra plaatsen zijn toegewezen?

**Comment by Sambego** [comment]
Done!

**Comment by bramus** [comment]
Ter info: Als je op het kaartje klikt vanop https://www.meetup.com/preview/Fronteers-BE/events/244086094 komt het niet goed op Google Maps:

- spelfout in straatnaam
- der staat "meetup62" tussenin het adres

Correcte adres is `Brusselsesteenweg 347, Asse, België` ;)

**Comment by Sambego** [comment]
@bramus ik heb het adres aangepast, is het nu juist?

**Comment by bramus** [comment]
Looking good! 👌

**Comment by IbeVanmeenen** [comment]
@bengie klopt dat jij voor de bedankingen zal kijken? :-)

**Comment by bengie** [comment]
@IbeVanmeenen liefst niet. Liever iemand die nog contact heeft met Fronteers NL voor de terugbetaling. Anders een heel gedoe..

**Comment by bramus** [comment]
Ik moet niks hebben hoor, no worries there ;)

**Comment by joggink** [comment]
ik ook niet

**Comment by IbeVanmeenen** [comment]
Geen probleem, ik kijk wel nog voor iets ;-)

**Comment by bengie** [comment]
de video's van de prezos
pt1: intro + @joggink  https://youtu.be/cZAazcPBDU0
pt2: @bramus https://youtu.be/jBqB3p2-8k0

**Comment by IbeVanmeenen** [comment]
@bengie Super! Thanks ✨
