### ISSUE TITLE
2018-02-22 - Creativity Gym - Mechelen

### ISSUE THREAD

**Issue by Sambego** [fronteersbe/meetups#31]
- [x] Contactpersoon Fronteers: @sambego
- [x] Contactpersoon Locatie: david.heerinckx@thomasmore.be
- [x] Locatie: Thomas More Mechelen
- [x] Capaciteit: 100
- [x] Presentatie 1: Frederick Vanbrabant
- [x] Presentatie 2: Partrick Debois
- [x] Detailpagina: https://fronteers.nl/bijeenkomsten/2018/meetup-bij-creativity-gym
- [x] Meetup.com
- [ ] Verantwoordelijke bedankingen: ?
- [x] Catering: Nee - Zelf voorzien

**Comment by iamgoodbytes** [comment]
Capaciteit: 100

**Comment by iamgoodbytes** [comment]
Hi @Sambego, ja hoor David zal dat opvolgen. Ik ben z'n collega en volg mee op waar nodig.
