### ISSUE TITLE
2018-05-17 - Sweet Mustard - Kortrijk

### ISSUE THREAD

**Issue by IbeVanmeenen** [fronteersbe/meetups#34]
- [x] Contactpersoon Fronteers: @IbeVanmeenen
- [x] Contactpersoon Locatie: @IbeVanmeenen
- [x] Locatie: Sweet Mustard - De Kien - Kortrijk
- [x] Capaciteit: 40
- [x] Presentatie 1: @IbeVanmeenen - Demystifying the future of CSS
- [x] Presentatie 2: @roelvangils - Inclusive Design in the Digital Age
- [x] Detailpagina: https://fronteers.nl/bijeenkomsten/2018/meetup-bij-sweet-mustard
- [x] Meetup.com: https://www.meetup.com/Fronteers-BE/events/248805497/
- [x] Verantwoordelijke bedankingen: @IbeVanmeenen
- [x] Catering: Ja

**Comment by roelvangils** [comment]
Super dat jullie weer gaan spreken :) Ik vind het nu wel een beetje jammer dat deze dan net op Global Accessibility Awareness Day valt, en dat we daar dan geen gebruik van maken.

**Comment by Sambego** [comment]
Daar heb je helemaal gelijk in @roelvangils! Het is door een samenloop van omstandigheden dat we de meetup van deze maand naar volgende maand hebbenmoeten verschuiven. Ik was het feit van de Accessibility Awareness dat oom even vergeten 🙊 Ik ben zelf spreker als noodoplossing :) Jij mag die taak zeker van me overnemen en jou talk rond accessibility komen geven als je dat zou willen. Met veel plezier zelfs, want jouw talks zijn altijd de moeite!
