### ISSUE TITLE
2018-??-?? - ?? - Limburg

### ISSUE THREAD

**Issue by IbeVanmeenen** [fronteersbe/meetups#35]
- [x] Contactpersoon Fronteers: Sam Bellen (@sambego)
- [ ] Contactpersoon Locatie: ?
- [ ] Locatie: ?
- [ ] Capaciteit: ?
- [ ] Presentatie 1: ?
- [ ] Presentatie 2: ?
- [ ] Detailpagina: ?
- [ ] Meetup.com
- [ ] Verantwoordelijke bedankingen: ?
- [ ] Catering: ?

**Comment by bengie** [comment]
Anders eens polsen bij de mannen van Inventis?
