### ISSUE TITLE
2018-12-19 - TVH Air - Waregem

### ISSUE THREAD

**Issue by joggink** [fronteersbe/meetups#38]
- [x] Contactpersoon Fronteers: @IbeVanmeenen 
- [x] Contactpersoon Locatie: @IbeVanmeenen 
- [x] Locatie: Vichtseweg 129 Waregem
- [x] Capaciteit: 30 / 40 man
- [x] Presentatie 1: Roel Van Gils (voorprogramma)
- [x] Presentatie 2: Mathias Bynens (main act)
- [x] Meetup.com
- [x] Detailpagina: https://www.meetup.com/Fronteers-BE/events/256909829/
- [ ] Verantwoordelijke bedankingen: ?
- [x] Catering: TVH (@IbeVanmeenen via Cliff Depreytere)

**Comment by joggink** [comment]
@mathiasbynens mss zin om iets te vertellen? Of om uwen fronteers talk eens te komen proberen ;)

**Comment by mathiasbynens** [comment]
Zin wel! Maar ik zou daarvoor speciaal vanuit München moeten afkomen, en da’s niet helemaal praktisch… Al enig idee van de datum?

**Comment by joggink** [comment]
Zijn er toevallig dagen dat je in het land bent? Of mochten we je reis vergoeden?

**Comment by mathiasbynens** [comment]
Ik ben op woensdag 19 december en vrijdag 21 december beschikbaar en in het land!

**Comment by joggink** [comment]
TVH lukt normaal nog. @IbeVanmeenen heeft wel gisteren hier zijn talk gedaan over houdini...

Dus nog een tweede spreker zoeken dan

**Comment by roelvangils** [comment]
Oei, ik dacht net te zeggen: wat een super combo, @mathiasbynens en @IbeVanmeenen! Ik denk niet dat ik daar tegenop kan hoor.

**Comment by bramus** [comment]
Maar Roel, gij gaat dat zeker goed doen! Mocht je toch niet zien zitten: oproep via Twitter anders?

**Comment by bramus** [comment]
Zie net dat @IbeVanmeenen zijn talk [op de vorige bijeenkomst](https://github.com/fronteersbe/meetups/issues/34) gegeven heeft (🤦‍♂️) … video staat net online ook — https://www.youtube.com/watch?v=M7p7zIBpJpA

**Comment by IbeVanmeenen** [comment]
@bramus die had ik idd "as practice" al eens op een Fronteers meetup gegeven.

**Comment by IbeVanmeenen** [comment]
@mathiasbynens Alright, super! Dan zouden we graag op 19 december een stukje van je tijd willen reserveren. Goed als we je talk rond 19:20 inplannen? Oh, en heb je al een title en short intro beschikbaar, dan zet ik deze ook alvast op de meetup pagina.

**Comment by mathiasbynens** [comment]
19:20 moet lukken!

Ik kan eventueel mijn presentatie over "V8 engine internals for JavaScript developers: arrays" geven. Klinkt dat interessant?

**Comment by roelvangils** [comment]
Dat klinkt excellent!

Mathias, het zou een eer zijn om jouw voorprogramma te komen verzorgen :) Ik heb een korte accessibility talk over Speech CSS, Voice Heuristics en wat best practices.

**Comment by roelvangils** [comment]
De meetup-pagina is gepimpt: https://www.meetup.com/Fronteers-BE/events/256909829/. Moeten we ook officiële aankondiging op Fronteers.nl doen, of doen we dat niet meer?

**Comment by joggink** [comment]
@roelvangils @IbeVanmeenen Kan er iemand het logo op de meetup pagina etc.  aanpassen naar het officiële logo aub? 
![logo tvh-safespace_cmyk jpec](https://user-images.githubusercontent.com/88325/49728953-64105d00-fc74-11e8-9e7f-b02be82fb406.jpg)
[logo TVH-safespace_cmyk.pdf](https://github.com/fronteersbe/meetups/files/2662874/logo.TVH-safespace_cmyk.pdf)

**Comment by roelvangils** [comment]
Allez, een kerstlogo :) Of mag dat niet van de styleguide?

**Comment by roelvangils** [comment]
Hardvochtige mensen :)

☃️☃️☃️☃️☃️☃️☃️☃️☃️☃️☃️☃️☃️☃️
