### ISSUE TITLE
2019-10-24 - Studio Hyperdrive - Gent

### ISSUE THREAD

**Issue by benjaminnaesen** [fronteersbe/meetups#39]
- [x] Contactpersoon Fronteers: Sam Bellen (@Sambego )
- [x] Contactpersonen Locatie: Kim Janssens (@kimjanssens, kim.janssens@studiohyperdrive.be)
- [x] Locatie: Sint-Salvatorstraat 18/302, 9000 Ghent, Belgium
- [x] Capaciteit: 40
- [x] Presentatie 1: @roelvangils: Designing the hidden User Experience
- [x] Presentatie 2: @tomopdebeeck en @DenisValcke: Remember that developers are users too
- [x] Detailpagina: https://fronteers.nl/bijeenkomsten/2019/meetup-bij-studio-hyperdrive-op-donderdag-24-oktober-2019
- [x] Meetup.com: https://www.meetup.com/Fronteers-BE/events/264516015/
- [x] Verantwoordelijke bedankingen: @Sambego 
- [x] Catering: Yes

**Comment by IbeVanmeenen** [comment]
@benjaminnaesen Via @Sambego te horen gekregen dat jullie deze graag op 24/11 zouden organiseren. Is dit nog steeds OK voor jullie?

**Comment by kimjanssens** [comment]
@IbeVanmeenen de datum is een maand verlaat naar 24/11, maar wij wachten nog op een officiele OK van onze bazen. Wij houden jullie nog op de hoogte

**Comment by Sambego** [comment]
@IbeVanmeenen bedoel je niet 24/10?

**Comment by kimjanssens** [comment]
24/10 inderdaad :) excuses

**Comment by roelvangils** [comment]
Boys, zouden jullie interesse hebben in een (deep dive) accessibility talk? Iets over het Accessibility Object Model bijvoorbeeld. Ik heb er nog wel eens zin in, zeker nu het nog eens in Gent is.

**Comment by IbeVanmeenen** [comment]
@Sambego @kimjanssens Om alle verwarring te vermijden: De datum blijft 24/10/2019 dan? :-)

**Comment by kimjanssens** [comment]
Presentatie 1: Fronteers accessiblity talk

Presentatie 2: Langs onze kant zouden we graag een mix voorzien van technisch / niet technisch. Denis en Tom, twee collega’s, zouden onze evolutie als Studio Hypderdrive wat toelichten vanuit een developer standpunt. (Community, Project werking, Codebase)

**Comment by Sambego** [comment]
@roelvangils zie je het nog zitten om je deep dive accessibility talk te komen geven in Oktober?

**Comment by roelvangils** [comment]
@Sambego Ja, maar laat ik het toch geen 'deep dive' noemen 🙂 Ik moet in die periode een andere talk geven die 'Designing the hidden User Experience' zal heten. Die zal gaan over de samenwerking tussen UI Designers en developers, met praktijktips om beter aan elkaars (wederzijdse) verwachtingen te voldoen (om zo tot een toegankelijker resultaat te komen). Veel code komt er niet aan te pas, maar dat hoeft misschien ook niet altijd.

@kimjanssens @benjaminnaesen Ik zag dat jullie op Medium ook een heel [mooi stuk over accessibility](https://medium.com/@studiohyperdrv/hang-on-let-me-accessibilize-this-3a412903b5d)  schreven. Eventueel kunnen we ergens linken vinden tussen de presentaties. Hebben jullie cases waarin accessibility een belangrijke rol speelde?

**Comment by Sambego** [comment]
@kimjanssens @benjaminnaesen Een preview van de eventpagina kan je hier vinden: https://www.meetup.com/Fronteers-BE/events/264516015/

@roelvangils ik heb voorlopig je talk die je hierboven vermelde gebruikt, als je hier aanpassingen wilt aan maken, laat het maar weten. Als alles ok is publish ik de event pagina :)

cc @IbeVanmeenen zo ben je ook mee met het verhaal :)

**Comment by roelvangils** [comment]
@Sambego Super! Ik zag een dt-foutje in het paragraafje over mijn talk 😉 Ik heb het ook ietsje anders geformuleerd. Die 'rots in de branding' mag wel blijven staan. 😜 

> Beginnen doen we met Roel Van Gils, België's rots in de branding op accessibility-vlak. Hij deelt ervaringen en praktijktips over hoe UI Designers en Front-end developers betere vriendjes kunnen worden, door hun verwachtingen optimaal op elkaar af te stemmen. Dat komt de toegankelijkheid van het eindresultaat ten goede.

**Comment by Sambego** [comment]
@roelvangils Oeps, dt-fouten zijn niet mijn sterkste kant, merci om het te spotten!

**Comment by Sambego** [comment]
De event pagina is gepubliceerd: https://www.meetup.com/Fronteers-BE/events/264516015/

**Comment by joggink** [comment]
binnenkort inplannen mag er af ;)

**Comment by kimjanssens** [comment]
@roelvangils zou je mij een foto kunnen bezorgen van jezelf die wij zouden kunnen gebruiken om je aan te kondigen als speaker? Je mag deze anders mailen naar kim.janssens@studiohyperdrive.be

**Comment by roelvangils** [comment]
Gebruik hiervoor gerust [deze foto](https://www.dropbox.com/s/j1xsnwrers63nyu/roel_3385x3385.jpg.zip?dl=1). Niet in full res best 😉
