### ISSUE TITLE
2019-12-12 - Sweet Mustard - Kortrijk

### ISSUE THREAD

**Issue by IbeVanmeenen** [fronteersbe/meetups#40]
- [x] Contactpersoon Fronteers: @IbeVanmeenen 
- [x] Contactpersoon Locatie: @IbeVanmeenen 
- [x] Locatie: Sweet Mustard - De Kien - Kortrijk
- [x] Capaciteit: 40
- [x] Presentatie 1: **Pieter Beulque**: Building a progressive enhanced Tweet embed with the latest browser build-ins 
- [x] Presentatie 2: **Mike Seghers**:  Adapting to new technology
- [ ] Detailpagina: ?
- [x] Meetup.com: https://www.meetup.com/Fronteers-BE/events/266487825/
- [x] Verantwoordelijke bedankingen: @IbeVanmeenen 
- [x] Catering: Ja

**Comment by Wolfr** [comment]
Cool!
