### ISSUE TITLE
?-09-2020 - Combell - Gent

### ISSUE THREAD

**Issue by coudenysj** [fronteersbe/meetups#41]
- [ ] Contactpersoon Fronteers: @Mangamaui 
- [ ] Contactpersoon Locatie: @coudenysj
- [ ] Locatie: Skaldenstraat 121, 9042 Gent
- [ ] Capaciteit: 30-50
- [ ] Presentatie 1: ?
- [ ] Presentatie 2: ?
- [ ] Detailpagina: ?
- [ ] Meetup.com
- [ ] Verantwoordelijke bedankingen: ?
- [ ] Catering: ?

**Comment by coudenysj** [comment]
Ik werd doorverwezen naar hier door @joggink. Jullie zijn welkom bij Combell om een meetup te organiseren!

**Comment by coudenysj** [comment]
Ping @Mangamaui, @IbeVanmeenen, @Sambego

**Comment by joggink** [comment]
Er gebeurt precies niet veel :/

**Comment by bramus** [comment]
Heb ik m'n "ESNext: Proposals to look forward to" al op Fronteers gegeven? Dacht het niet. Zie'k wel zitten om nog eens te doen, zeker nu enkele proposals naar Stage-4 gegaan zijn.

Kan ook nog over m'n ervaringen met Google Cloud Build en Google Cloud Run leuteren, maar lijkt me het verkeerde publiek te zijn ;-)

**Comment by coudenysj** [comment]
@bramus Voor uw Google Cloud Run leutering, zijt ge altijd welkom bij @PHP-WVL ;)

**Comment by Mangamaui** [comment]
Niet iedereen heeft Github notificaties aanstaan @joggink 😉

@coudenysj Ik ga u 1 van dees terug contacteren! 😁 Is de organisers slack goed of toch liever via mail?

**Comment by coudenysj** [comment]
Slack is goed :)

**Comment by IbeVanmeenen** [comment]
@coudenysj We zijn van plan om een Fronteers Meetup @ Gent te organiseren ergens in september. Zijn we nog welkom bij jullie? :-)

**Comment by coudenysj** [comment]
@IbeVanmeenen zijt maar zeker!

**Comment by IbeVanmeenen** [comment]
Super :-)

**Comment by joggink** [comment]
bij In The Pocket is er ook altijd plaats ;)
