### ISSUE TITLE
05-03-2020 - Cronos - Leuven

### ISSUE THREAD

**Issue by Mangamaui** [fronteersbe/meetups#42]
- [x] Contactpersoon Fronteers: Claudia @Mangamaui 
- [x] Contactpersoon Locatie: Annelies Kloet
- [x] Locatie: Gaston Geenslaan 11/B4, 3000 Leuven
- [x] Capaciteit: 50 - 60 (wordt nog bevestigd)
- [x] Presentatie 1: @g00glen00b / Dimitri Mestdagh  - Wordpress to Gatsby
- [x] Presentatie 2: @samvloeberghs -  Implementing powerful offline experiences with Workbox
- [ ] Detailpagina: ?
- [x] Meetup.com https://www.meetup.com/Fronteers-BE/events/267803949/
- [ ] Verantwoordelijke bedankingen: ?
- [x] Catering: Nee

**Comment by wesleylancel** [comment]
Locatie mag gerust bij Yappa!
