### ISSUE TITLE
?-04-2020 - ? - Hasselt

### ISSUE THREAD

**Issue by Mangamaui** [fronteersbe/meetups#43]
- [ ] Contactpersoon Fronteers: @Sambego 
- [ ] Contactpersoon Locatie: ?
- [ ] Locatie: ?
- [ ] Capaciteit: ?
- [ ] Presentatie 1: ?
- [ ] Presentatie 2: ?
- [ ] Detailpagina: ?
- [ ] Meetup.com
- [ ] Verantwoordelijke bedankingen: ?
- [ ] Catering: ?

**Comment by IbeVanmeenen** [comment]
Corda Campus
