### ISSUE TITLE
?-05-2020 - ? - Mechelen

### ISSUE THREAD

**Issue by Mangamaui** [fronteersbe/meetups#44]
- [ ] Contactpersoon Fronteers: ?
- [ ] Contactpersoon Locatie: ?
- [ ] Locatie: ?
- [ ] Capaciteit: ?
- [ ] Presentatie 1: ?
- [ ] Presentatie 2: ?
- [ ] Detailpagina: ?
- [ ] Meetup.com
- [ ] Verantwoordelijke bedankingen: ?
- [ ] Catering: ?

**Comment by IbeVanmeenen** [comment]
Navragen @ Creativity Gym
