### ISSUE TITLE
?-11-2020 - ? - West-Vlaanderen

### ISSUE THREAD

**Issue by Mangamaui** [fronteersbe/meetups#45]
- [ ] Contactpersoon Fronteers: @IbeVanmeenen 
- [ ] Contactpersoon Locatie: ?
- [ ] Locatie: ?
- [ ] Capaciteit: ?
- [ ] Presentatie 1: ?
- [ ] Presentatie 2: ?
- [ ] Detailpagina: ?
- [ ] Meetup.com
- [ ] Verantwoordelijke bedankingen: ?
- [ ] Catering: ?

**Comment by IbeVanmeenen** [comment]
Kortrijk of Brugge

**Comment by joggink** [comment]
Brugge eens polsen bij Guideline Belgium. Ik wil wel checken anders :)

**Comment by IbeVanmeenen** [comment]
@joggink Super, mag je zeker als eens navragen bij hen! :-)

**Comment by myle-truong** [comment]
count me on please, i want to join

**Comment by Mangamaui** [comment]
Not sure what you mean @myle-truong, but this is not an event yet. 🙂 This is actually where we discuss our plans for future events. If you want to join an event [check our meetup page](https://www.meetup.com/Fronteers-BE/)

**Comment by myle-truong** [comment]
Thank for your reply. I mean the event in Brugge. Thank for recommend other events too. I am newbie and new in town too then that could be wonderful chance to meet the seniors.
