### ISSUE TITLE
??-??-2021

### ISSUE THREAD

**Issue by Sambego** [fronteersbe/meetups#48]
- [x] Contactpersoon Fronteers: @sambego
- [x] Contactpersoon Locatie: Marie Beckers (LinkedIn)
- [x] Locatie: Ambassify, Tervantstraat 2b, 3583 Beringen
- [ ] Capaciteit: ?
- [ ] Presentatie 1: ?
- [ ] Presentatie 2: ?
- [ ] Detailpagina: ?
- [ ] Meetup.com
- [ ] Verantwoordelijke bedankingen: ?
- [ ] Catering: ?

**Comment by bramus** [comment]
In het geval we ooit weer fysiek samen mogen komen, dan kom ik graag mee af met een nieuwe talk over de CSS Cascade ;)

**Comment by roelvangils** [comment]
In Limburg dan nog wel! Ik kom af! We maken er een weekend van :)

**Comment by Sambego** [comment]
Een weekend met Limburgse vlaai! 🥧
