### ISSUE TITLE
xx-xx-2014: Nascom

### ISSUE THREAD

**Issue by mathiasbynens** [fronteersbe/meetups#6]
- [x] Contactpersoon: Glenn Billiau `<billiaug@gmail.com>`
- [ ] Locatie: Nascom, Genk
- [ ] Capaciteit: ?? personen
- [ ] Presentatie 1: _TBA_ door TBA
- [ ] Presentatie 2: _TBA_ door TBA
- [ ] Detailpagina: wordt `http://fronteers.nl/bijeenkomsten/2014/nascom`
- [ ] Blog-post: {URL}
- [ ] Lanyrd-pagina: wordt `http://lanyrd.com/2014/fronteersbe-nascom/`

**Comment by IbeVanmeenen** [comment]
Verwijderen?
